### ISSUE TITLE
Main vs develop branch

### ISSUE THREAD

**Issue by ThomDietrich** [rejuvenate/lovelace-sun-card#2]
The original repository has a main branch and a develop branch with a few good additions.

I suggest to ff-merge develop back into main, either immediately or after it was tested. Anyhow, all PRs should be created against develop.

**Comment by selfish** [comment]
Hello everyone,

I concur with the idea of leveraging the content from the develop branch, which, to my knowledge, @avataar has already incorporated into their branch. In light of this, I would like to initiate a discussion on branching and merge strategies for our repository.

Considering the nature and scale of our project, I believe maintaining a separate dev branch might not be necessary, as we are not dealing with extensive or critical releases. It seems more fitting for a project like ours to expedite updates as they become available. Thus, I propose that we eliminate additional branches and focus on the main branch for a more streamlined workflow. We could then release updates automatically upon each change (I have implemented this in my fork).

Furthermore, in line with contemporary best practices, I personally advocate for rebasing over merging. This approach can help maintain a cleaner commit history and simplify our collaboration process. Also, it retains the contribution better, inviting more contributors as the "credit" for contributions is presented clearly.

I welcome your thoughts and suggestions on these matters.

**Comment by avataar** [comment]
I agree with all of the above points.

**Comment by selfish** [comment]
Given the agreement from @avataar I've updated the repo config to use rebase-merges.
@ThomDietrich if you have any objection, let's discuss.

**Comment by ThomDietrich** [comment]
Great, we agree :) There is no need for a separate dev branch in this project. Releases should be published based on tags though, @selfish do you agree?

> I personally advocate for rebasing over merging

In the particular case, we were talking about the same thing! The dev branch is a clean branch going off the main branch. There are no newer commits on the main branch. Therefore a rebase is technically not necessary, hence why I suggested a fast-forward-merge :)

**Comment by selfish** [comment]
Yeah, no problem. You're very right to re-enable it.
I would say let's use them carefully. Personally, my commit messages serve as an actual changelog, which my CI translates to the release notification. But for hasty commits like these, I agree that it's a much better idea to squash it into a single one, with a reasonable message.

**Comment by ThomDietrich** [comment]
Of course let's be considerate of all opinions going forward :)

Btw food for thought: If everybody abides to good open source contribution rules, a (typical small) PR should implement exactly one idea, therefore it can be squashed into a single commit.

**Comment by ThomDietrich** [comment]
Develop branch successfully merged. Let's get to the next steps! 🎉
